
-- to spin a new FlaskReactor DB using the latest changes:
-- create a database called 'test', run the following command alone, and then run the rest of the file.

DROP DATABASE IF EXISTS postgres WITH (FORCE);

-- following line will delete all data, use with intent
--drop schema if exists flaskreactor cascade;

create schema flaskreactor;

create table flaskreactor.quadradius_games (
    id text PRIMARY KEY,
    player1 text NOT NULL,
    player2 text NOT NULL,
    player1_color text NOT NULL,
    player2_color text NOT NULL,
    boardstate JSON NOT NULL,
    active_player text NOT NULL,
    completed boolean NOT NULL,
    time_started timestamp NOT NULL,
    last_move timestamp,
    time_ended timestamp,
    winner text
);

create table flaskreactor.chess_games (
    id text PRIMARY KEY,
    white_player text NOT NULL,
    black_player text NOT NULL,
    boardstate JSON NOT NULL,
    completed boolean NOT NULL,
    time_started timestamp NOT NULL,
    last_move timestamp,
    time_ended timestamp,
    player_turn text NOT NULL, -- username of active player
    winner text, 
    notation text,
    whitekingmoved boolean NOT NULL DEFAULT false,
    blackkingmoved boolean NOT NULL DEFAULT false,
    wqr_moved boolean NOT NULL DEFAULT false,
    wkr_moved boolean NOT NULL DEFAULT false,
    bqr_moved boolean NOT NULL DEFAULT false,
    bkr_moved boolean NOT NULL DEFAULT false,
    pawn_leapt boolean,
    pawn_leap_col int
);

create table flaskreactor.tictactoe_games (
    id text PRIMARY KEY,
    x_player text NOT NULL,
    o_player text NOT NULL,
    completed boolean,
    time_started timestamp NOT NULL,
    last_move timestamp,
    time_ended timestamp,
    player_turn text NOT NULL,
    winner text,
    boardstate char[] NOT NULL
);

create table flaskreactor.users (
    name text NOT NULL,
    email text,
    id text  NOT NULL,
    password_hash text NOT NULL,
    ws_token text NOT NULL,
    quad_color_pref text NOT NULL,
    quad_color_backup text NOT NULL
);

create table flaskreactor.stats (
        userId text,
        ttt_games_played integer,
        ttt_wins integer,
        ttt_win_percent integer,
        ttt_played_white integer,
        ttt_played_black integer,
        ttt_won_white integer,
        ttt_won_black integer
);

create table flaskreactor.messages (
    gameId text NOT NULL,
    index INT GENERATED BY DEFAULT AS IDENTITY, -- insane.
    content text NOT NULL,
    username text NOT NULL
);

-- you will need to edit pg_hba.conf to use method 'password' or 'trust' for local ipv4 and 6 connections. adding a new entry does not work AFAIK.
