

create table flaskreactor.chess_games (
    id text PRIMARY KEY,
    white_player text,
    black_player text,
    boardstate JSON,
    completed boolean,
    time_started timestamp,
    last_move timestamp,
    time_ended timestamp,
    player_turn text, -- username of active player
    winner text, 
    notation text,
    whitekingmoved boolean,
    blackkingmoved boolean,
    wqr_moved boolean,
    wkr_moved boolean,
    bqr_moved boolean,
    bkr_moved boolean,
    pawn_leapt boolean,
    pawn_leap_col int
);

create table flaskreactor.tictactoe_games (
    id text PRIMARY KEY,
    x_player text,
    o_player text,
    completed boolean,
    time_started timestamp,
    last_move timestamp,
    time_ended timestamp,
    player_turn text,
    winner text,
    boardstate "char"[],
);

create table flaskreactor.users (
    name text,
    email text,
    id text,
    password_hash text,
    ws_token text
);

create table flaskreactor.stats (
        userId text,
        ttt_games_played integer,
        ttt_wins integer,
        ttt_win_percent integer,
        ttt_played_white integer,
        ttt_played_black integer,
        ttt_won_white integer,
        ttt_won_black integer
);

create table flaskreactor.messages (
    gameId text NOT NULL,
    index INT GENERATED BY DEFAULT AS IDENTITY, -- insane.
    content text NOT NULL,
    userid text NOT NULL
)